style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false

complexity:
  TooManyFunctions:
    active: false
  ComplexMethod:
    active: false
    threshold: 20

naming:
  VariableNaming:
    active: false